# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dima/works/DM-Office

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dima/works/DM-Office

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dima/works/DM-Office/CMakeFiles /home/dima/works/DM-Office//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dima/works/DM-Office/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dmoffice

# Build rule for target.
dmoffice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dmoffice
.PHONY : dmoffice

# fast build rule for target.
dmoffice/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/build
.PHONY : dmoffice/fast

src/Widgets/AppWin/AppWin.o: src/Widgets/AppWin/AppWin.cpp.o
.PHONY : src/Widgets/AppWin/AppWin.o

# target to build an object file
src/Widgets/AppWin/AppWin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/AppWin/AppWin.cpp.o
.PHONY : src/Widgets/AppWin/AppWin.cpp.o

src/Widgets/AppWin/AppWin.i: src/Widgets/AppWin/AppWin.cpp.i
.PHONY : src/Widgets/AppWin/AppWin.i

# target to preprocess a source file
src/Widgets/AppWin/AppWin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/AppWin/AppWin.cpp.i
.PHONY : src/Widgets/AppWin/AppWin.cpp.i

src/Widgets/AppWin/AppWin.s: src/Widgets/AppWin/AppWin.cpp.s
.PHONY : src/Widgets/AppWin/AppWin.s

# target to generate assembly for a file
src/Widgets/AppWin/AppWin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/AppWin/AppWin.cpp.s
.PHONY : src/Widgets/AppWin/AppWin.cpp.s

src/Widgets/custom/conteiners/MHeaderBar.o: src/Widgets/custom/conteiners/MHeaderBar.cpp.o
.PHONY : src/Widgets/custom/conteiners/MHeaderBar.o

# target to build an object file
src/Widgets/custom/conteiners/MHeaderBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/conteiners/MHeaderBar.cpp.o
.PHONY : src/Widgets/custom/conteiners/MHeaderBar.cpp.o

src/Widgets/custom/conteiners/MHeaderBar.i: src/Widgets/custom/conteiners/MHeaderBar.cpp.i
.PHONY : src/Widgets/custom/conteiners/MHeaderBar.i

# target to preprocess a source file
src/Widgets/custom/conteiners/MHeaderBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/conteiners/MHeaderBar.cpp.i
.PHONY : src/Widgets/custom/conteiners/MHeaderBar.cpp.i

src/Widgets/custom/conteiners/MHeaderBar.s: src/Widgets/custom/conteiners/MHeaderBar.cpp.s
.PHONY : src/Widgets/custom/conteiners/MHeaderBar.s

# target to generate assembly for a file
src/Widgets/custom/conteiners/MHeaderBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/conteiners/MHeaderBar.cpp.s
.PHONY : src/Widgets/custom/conteiners/MHeaderBar.cpp.s

src/Widgets/custom/documents/EditTextView.o: src/Widgets/custom/documents/EditTextView.cpp.o
.PHONY : src/Widgets/custom/documents/EditTextView.o

# target to build an object file
src/Widgets/custom/documents/EditTextView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/EditTextView.cpp.o
.PHONY : src/Widgets/custom/documents/EditTextView.cpp.o

src/Widgets/custom/documents/EditTextView.i: src/Widgets/custom/documents/EditTextView.cpp.i
.PHONY : src/Widgets/custom/documents/EditTextView.i

# target to preprocess a source file
src/Widgets/custom/documents/EditTextView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/EditTextView.cpp.i
.PHONY : src/Widgets/custom/documents/EditTextView.cpp.i

src/Widgets/custom/documents/EditTextView.s: src/Widgets/custom/documents/EditTextView.cpp.s
.PHONY : src/Widgets/custom/documents/EditTextView.s

# target to generate assembly for a file
src/Widgets/custom/documents/EditTextView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/EditTextView.cpp.s
.PHONY : src/Widgets/custom/documents/EditTextView.cpp.s

src/Widgets/custom/documents/PresentationDocument.o: src/Widgets/custom/documents/PresentationDocument.cpp.o
.PHONY : src/Widgets/custom/documents/PresentationDocument.o

# target to build an object file
src/Widgets/custom/documents/PresentationDocument.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/PresentationDocument.cpp.o
.PHONY : src/Widgets/custom/documents/PresentationDocument.cpp.o

src/Widgets/custom/documents/PresentationDocument.i: src/Widgets/custom/documents/PresentationDocument.cpp.i
.PHONY : src/Widgets/custom/documents/PresentationDocument.i

# target to preprocess a source file
src/Widgets/custom/documents/PresentationDocument.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/PresentationDocument.cpp.i
.PHONY : src/Widgets/custom/documents/PresentationDocument.cpp.i

src/Widgets/custom/documents/PresentationDocument.s: src/Widgets/custom/documents/PresentationDocument.cpp.s
.PHONY : src/Widgets/custom/documents/PresentationDocument.s

# target to generate assembly for a file
src/Widgets/custom/documents/PresentationDocument.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/PresentationDocument.cpp.s
.PHONY : src/Widgets/custom/documents/PresentationDocument.cpp.s

src/Widgets/custom/documents/Spreadsheet.o: src/Widgets/custom/documents/Spreadsheet.cpp.o
.PHONY : src/Widgets/custom/documents/Spreadsheet.o

# target to build an object file
src/Widgets/custom/documents/Spreadsheet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/Spreadsheet.cpp.o
.PHONY : src/Widgets/custom/documents/Spreadsheet.cpp.o

src/Widgets/custom/documents/Spreadsheet.i: src/Widgets/custom/documents/Spreadsheet.cpp.i
.PHONY : src/Widgets/custom/documents/Spreadsheet.i

# target to preprocess a source file
src/Widgets/custom/documents/Spreadsheet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/Spreadsheet.cpp.i
.PHONY : src/Widgets/custom/documents/Spreadsheet.cpp.i

src/Widgets/custom/documents/Spreadsheet.s: src/Widgets/custom/documents/Spreadsheet.cpp.s
.PHONY : src/Widgets/custom/documents/Spreadsheet.s

# target to generate assembly for a file
src/Widgets/custom/documents/Spreadsheet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/Spreadsheet.cpp.s
.PHONY : src/Widgets/custom/documents/Spreadsheet.cpp.s

src/Widgets/custom/documents/TextDocument.o: src/Widgets/custom/documents/TextDocument.cpp.o
.PHONY : src/Widgets/custom/documents/TextDocument.o

# target to build an object file
src/Widgets/custom/documents/TextDocument.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/TextDocument.cpp.o
.PHONY : src/Widgets/custom/documents/TextDocument.cpp.o

src/Widgets/custom/documents/TextDocument.i: src/Widgets/custom/documents/TextDocument.cpp.i
.PHONY : src/Widgets/custom/documents/TextDocument.i

# target to preprocess a source file
src/Widgets/custom/documents/TextDocument.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/TextDocument.cpp.i
.PHONY : src/Widgets/custom/documents/TextDocument.cpp.i

src/Widgets/custom/documents/TextDocument.s: src/Widgets/custom/documents/TextDocument.cpp.s
.PHONY : src/Widgets/custom/documents/TextDocument.s

# target to generate assembly for a file
src/Widgets/custom/documents/TextDocument.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/Widgets/custom/documents/TextDocument.cpp.s
.PHONY : src/Widgets/custom/documents/TextDocument.cpp.s

src/classes/CssLoader.o: src/classes/CssLoader.cpp.o
.PHONY : src/classes/CssLoader.o

# target to build an object file
src/classes/CssLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/classes/CssLoader.cpp.o
.PHONY : src/classes/CssLoader.cpp.o

src/classes/CssLoader.i: src/classes/CssLoader.cpp.i
.PHONY : src/classes/CssLoader.i

# target to preprocess a source file
src/classes/CssLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/classes/CssLoader.cpp.i
.PHONY : src/classes/CssLoader.cpp.i

src/classes/CssLoader.s: src/classes/CssLoader.cpp.s
.PHONY : src/classes/CssLoader.s

# target to generate assembly for a file
src/classes/CssLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/classes/CssLoader.cpp.s
.PHONY : src/classes/CssLoader.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dmoffice.dir/build.make CMakeFiles/dmoffice.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dmoffice"
	@echo "... src/Widgets/AppWin/AppWin.o"
	@echo "... src/Widgets/AppWin/AppWin.i"
	@echo "... src/Widgets/AppWin/AppWin.s"
	@echo "... src/Widgets/custom/conteiners/MHeaderBar.o"
	@echo "... src/Widgets/custom/conteiners/MHeaderBar.i"
	@echo "... src/Widgets/custom/conteiners/MHeaderBar.s"
	@echo "... src/Widgets/custom/documents/EditTextView.o"
	@echo "... src/Widgets/custom/documents/EditTextView.i"
	@echo "... src/Widgets/custom/documents/EditTextView.s"
	@echo "... src/Widgets/custom/documents/PresentationDocument.o"
	@echo "... src/Widgets/custom/documents/PresentationDocument.i"
	@echo "... src/Widgets/custom/documents/PresentationDocument.s"
	@echo "... src/Widgets/custom/documents/Spreadsheet.o"
	@echo "... src/Widgets/custom/documents/Spreadsheet.i"
	@echo "... src/Widgets/custom/documents/Spreadsheet.s"
	@echo "... src/Widgets/custom/documents/TextDocument.o"
	@echo "... src/Widgets/custom/documents/TextDocument.i"
	@echo "... src/Widgets/custom/documents/TextDocument.s"
	@echo "... src/classes/CssLoader.o"
	@echo "... src/classes/CssLoader.i"
	@echo "... src/classes/CssLoader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

